export const UsersActionTypes = {
  GET_USERS_PROCESSING: "GET_USERS_PROCESSING",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  GET_PENDING_USERS_PROCESSING: "GET_PENDING_USERS_PROCESSING",
  GET_PENDING_USERS_SUCCESS: "GET_PENDING_USERS_SUCCESS",
  GET_PENDING_USERS_FAILURE: "GET_PENDING_USERS_FAILURE",
};
